import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import joblib
import pandas as pd
from flask import Flask, render_template, request, jsonify
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

app = Flask(__name__)

# ── Paths — resolved relative to this file so they work on Vercel ──
_BASE = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(_BASE, "bank_model.pkl")
DATA_PATH  = os.path.join(_BASE, "finalisedaimlrawdataset.xlsx")

# ── Feature definitions ────────────────────────────────────────
FEATURE_COLUMNS = [
    "Customers_Count", "Transactions_Count", "Total_Deposits", "Total_Loans",
    "Staff_Count", "Location_Score", "Avg_Transaction", "Credit_Ratio",
    "Debit_Ratio", "Deposit_per_Customer", "Loan_per_Customer", "Branch_Revenue",
    "Customer_Growth_Rate", "Transaction_Frequency", "Average_Balance",
    "Loan_Default_Risk", "Customer_Satisfaction_Index", "Digital_Transactions",
    "Cash_Transactions", "Net_Profit", "Operational_Cost", "Staff_Productivity",
    "Branch_Utilization", "Risk_Adjusted_Return",
]

FEATURE_GROUPS = {
    "Branch Overview": [
        "Customers_Count", "Staff_Count", "Location_Score",
    ],
    "Transactions": [
        "Transactions_Count", "Avg_Transaction", "Transaction_Frequency",
        "Digital_Transactions", "Cash_Transactions",
    ],
    "Financial": [
        "Total_Deposits", "Total_Loans", "Branch_Revenue",
        "Net_Profit", "Operational_Cost",
    ],
    "Customers": [
        "Deposit_per_Customer", "Loan_per_Customer", "Customer_Growth_Rate",
        "Average_Balance", "Customer_Satisfaction_Index",
    ],
    "Risk & Returns": [
        "Credit_Ratio", "Debit_Ratio", "Loan_Default_Risk",
        "Staff_Productivity", "Branch_Utilization", "Risk_Adjusted_Return",
    ],
}

FEATURE_DESCRIPTIONS = {
    "Customers_Count":            "Total number of active customers at this branch",
    "Transactions_Count":         "Total transactions processed during the period",
    "Total_Deposits":             "Aggregate deposit portfolio in currency units",
    "Total_Loans":                "Aggregate loan portfolio in currency units",
    "Staff_Count":                "Full-time equivalent staff headcount",
    "Location_Score":             "Branch location quality index (scale 1-10)",
    "Avg_Transaction":            "Mean value per individual transaction",
    "Credit_Ratio":               "Credit exposure as a ratio of total assets (0-1)",
    "Debit_Ratio":                "Debit exposure as a ratio of total assets (0-1)",
    "Deposit_per_Customer":       "Average deposit amount per customer",
    "Loan_per_Customer":          "Average loan amount per customer",
    "Branch_Revenue":             "Total revenue generated by this branch",
    "Customer_Growth_Rate":       "Year-on-year customer growth rate (%)",
    "Transaction_Frequency":      "Average number of transactions per customer",
    "Average_Balance":            "Mean account balance across all customers",
    "Loan_Default_Risk":          "Probability-weighted loan default ratio",
    "Customer_Satisfaction_Index":"Aggregated customer satisfaction score (0-100)",
    "Digital_Transactions":       "Volume of digital and online transactions",
    "Cash_Transactions":          "Volume of cash-based counter transactions",
    "Net_Profit":                 "Net profit after all costs and provisions",
    "Operational_Cost":           "Total branch operating expenditure",
    "Staff_Productivity":         "Output-per-staff productivity composite index",
    "Branch_Utilization":         "Capacity utilisation rate (%)",
    "Risk_Adjusted_Return":       "Return on assets adjusted for risk exposure",
}

# ── Load model & dataset ─────────────────────────────────────
model  = joblib.load(MODEL_PATH)
raw_df = pd.read_excel(DATA_PATH)

# Replicate notebook preprocessing: fill NaN with column means first
training_df = raw_df.copy()
training_df.fillna(training_df.mean(numeric_only=True), inplace=True)

feature_means = training_df[FEATURE_COLUMNS].mean(numeric_only=True).to_dict()
feature_stds  = training_df[FEATURE_COLUMNS].std(numeric_only=True).to_dict()
feature_mins  = training_df[FEATURE_COLUMNS].min(numeric_only=True).to_dict()
feature_maxs  = training_df[FEATURE_COLUMNS].max(numeric_only=True).to_dict()

scores     = training_df["Performance_Score"]
SCORE_MIN  = float(scores.min())
SCORE_MAX  = float(scores.max())
SCORE_MEAN = float(scores.mean())
SCORE_STD  = float(scores.std())

# Tier distribution from actual dataset
TIER_DIST = {
    "Excellent":     int((scores >= 50).sum()),
    "Good":          int(((scores >= 42) & (scores < 50)).sum()),
    "Below Average": int(((scores >= 35) & (scores < 42)).sum()),
    "Poor":          int((scores < 35).sum()),
}

# Model evaluation — same split as notebook (random_state=42, test_size=0.2)
X_full = training_df[FEATURE_COLUMNS]
y_full = training_df["Performance_Score"]
_, X_te, _, y_te = train_test_split(X_full, y_full, test_size=0.2, random_state=42)
y_pred_te = model.predict(X_te.values)

MODEL_R2   = round(float(r2_score(y_te, y_pred_te)), 4)
MODEL_RMSE = round(float(mean_squared_error(y_te, y_pred_te) ** 0.5), 4)
N_TRAIN    = int(len(X_full) - len(X_te))
N_TEST     = int(len(X_te))


# ── Helpers ───────────────────────────────────────────────────
def _safe_float(val, fallback):
    """Convert val to float; return fallback on failure or non-finite result."""
    if val == "" or val is None:
        return fallback
    try:
        v = float(val)
        return v if (v == v and abs(v) != float("inf")) else fallback
    except (ValueError, TypeError):
        return fallback


def predict_performance(data: dict):
    """
    Build a numpy row from user-supplied data (empty → dataset mean),
    then run model inference.
    Returns (prediction: float, input_row: list[float])
    """
    row = [_safe_float(data.get(col, ""), feature_means[col]) for col in FEATURE_COLUMNS]
    X   = np.array(row, dtype=float).reshape(1, -1)
    return round(float(model.predict(X)[0]), 2), row


def get_tier(score: float):
    if score >= 50:
        return "Excellent", (
            "This branch is performing at an exceptional level, "
            "significantly above the portfolio average."
        )
    elif score >= 42:
        return "Good", (
            "This branch is performing above average with solid "
            "operational and financial metrics."
        )
    elif score >= 35:
        return "Below Average", (
            "Performance is below the portfolio average. "
            "Key operational areas require targeted improvement."
        )
    else:
        return "Poor", (
            "This branch requires immediate management intervention "
            "and a structured turnaround plan."
        )


def score_percentile(score: float) -> float:
    """Percentage of dataset branches that score below `score`."""
    return round(float((scores < score).mean() * 100), 1)


# ── Routes ────────────────────────────────────────────────────
@app.route("/", methods=["GET"])
def home():
    return render_template(
        "index.html",
        feature_groups=FEATURE_GROUPS,
        feature_descriptions=FEATURE_DESCRIPTIONS,
        features=FEATURE_COLUMNS,
        feature_means=feature_means,
        score_min=SCORE_MIN,
        score_max=SCORE_MAX,
        score_mean=round(SCORE_MEAN, 2),
        score_std=round(SCORE_STD, 2),
        n_samples=len(training_df),
    )


@app.route("/api/predict", methods=["POST"])
def api_predict():
    data = request.get_json(silent=True) or {}
    try:
        form_values = {col: data.get(col, "") for col in FEATURE_COLUMNS}
        prediction, input_row = predict_performance(form_values)
        tier, desc = get_tier(prediction)
        pct        = round((prediction - SCORE_MIN) / (SCORE_MAX - SCORE_MIN) * 100, 2)
        percentile = score_percentile(prediction)

        # Feature comparison: z-score vs dataset
        feature_comparison = []
        for col, user_val in zip(FEATURE_COLUMNS, input_row):
            mean = feature_means[col]
            std  = feature_stds.get(col, 1) or 1
            z    = (user_val - mean) / std
            feature_comparison.append({
                "feature":    col.replace("_", " "),
                "key":        col,
                "user_value": round(user_val, 4),
                "mean":       round(mean, 4),
                "z_score":    round(z, 3),
                "is_default": data.get(col, "") == "",
            })
        feature_comparison.sort(key=lambda x: abs(x["z_score"]), reverse=True)

        return jsonify({
            "prediction":        prediction,
            "tier":              tier,
            "description":       desc,
            "score_percent":     pct,
            "percentile":        percentile,
            "score_min":         SCORE_MIN,
            "score_max":         SCORE_MAX,
            "score_mean":        round(SCORE_MEAN, 2),
            "score_std":         round(SCORE_STD, 2),
            "model_r2":          MODEL_R2,
            "model_rmse":        MODEL_RMSE,
            "n_train":           N_TRAIN,
            "n_test":            N_TEST,
            "n_samples":         int(len(training_df)),
            "tier_dist":         TIER_DIST,
            "feature_comparison": feature_comparison[:12],
        })
    except Exception as exc:
        return jsonify({"error": str(exc)}), 400


@app.route("/api/sample-data", methods=["GET"])
def api_sample_data():
    row = training_df.sample(1).iloc[0]
    sample = {col: round(float(row[col]), 4) for col in FEATURE_COLUMNS if pd.notna(row[col])}
    if "Branch_ID" in training_df.columns:
        val = row["Branch_ID"]
        if pd.notna(val):
            try:
                # If it's a float like 1001.0, convert to int to display nicely
                sample["Branch_ID"] = int(val) if float(val).is_integer() else val
            except:
                sample["Branch_ID"] = str(val)
        else:
            sample["Branch_ID"] = ""
    return jsonify(sample)


@app.route("/api/branch-data/<branch_id>", methods=["GET"])
def api_branch_data(branch_id):
    try:
        # Convert to float first, then int if possible (e.g. "1871" or "1871.0" -> 1871)
        b_id = int(float(branch_id))
    except ValueError:
        b_id = str(branch_id).strip()

    # Search by direct matching
    matched = training_df[training_df["Branch_ID"] == b_id]
    if len(matched) == 0:
        # Fallback to string matching
        matched = training_df[training_df["Branch_ID"].astype(str).str.strip() == str(branch_id).strip()]

    if len(matched) == 0:
        return jsonify({"error": f"Branch '{branch_id}' not found in dataset"}), 404

    row = matched.iloc[0]
    sample = {col: round(float(row[col]), 4) for col in FEATURE_COLUMNS if pd.notna(row[col])}
    
    # Format Branch_ID nicely
    val = row["Branch_ID"]
    if pd.notna(val):
        try:
            sample["Branch_ID"] = int(val) if float(val).is_integer() else val
        except:
            sample["Branch_ID"] = str(val)
    else:
        sample["Branch_ID"] = branch_id

    return jsonify(sample)




@app.route("/api/model-stats", methods=["GET"])
def api_model_stats():
    return jsonify({
        "r2":        MODEL_R2,
        "rmse":      MODEL_RMSE,
        "n_train":   N_TRAIN,
        "n_test":    N_TEST,
        "n_features": len(FEATURE_COLUMNS),
        "algorithm": "Linear Regression",
        "score_min": SCORE_MIN,
        "score_max": SCORE_MAX,
        "score_mean": round(SCORE_MEAN, 2),
        "score_std":  round(SCORE_STD, 2),
        "tier_dist":  TIER_DIST,
    })


@app.route("/api/feature-stats", methods=["GET"])
def api_feature_stats():
    return jsonify({
        "means": {k: round(v, 4) for k, v in feature_means.items()},
        "stds":  {k: round(v, 4) for k, v in feature_stds.items()},
        "mins":  {k: round(v, 4) for k, v in feature_mins.items()},
        "maxs":  {k: round(v, 4) for k, v in feature_maxs.items()},
    })


if __name__ == "__main__":
    # Trigger model reload
    app.run(debug=True)